--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25/1/2022 12:47:02
-- Server version: 8.0.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS medi;

CREATE database IF NOT EXISTS medi;

--
-- Set default database
--
USE medi;

--
-- Create table `personas`
--
CREATE TABLE IF NOT EXISTS personas (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  apellido VARCHAR(45) NOT NULL,
  telefono VARCHAR(45) DEFAULT NULL,
  estado TINYINT DEFAULT 1,
  imagen VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2;

--
-- Create table `usuarios`
--
CREATE TABLE IF NOT EXISTS usuarios (
  id INT NOT NULL AUTO_INCREMENT,
  personas_id INT NOT NULL,
  login VARCHAR(45) NOT NULL,
  correo VARCHAR(250) NOT NULL,
  contrasena VARCHAR(45) NOT NULL,
  esttado ENUM('A','I','B') DEFAULT 'A',
  fallidos INT DEFAULT NULL,
  pin CHAR(4) DEFAULT NULL,
  tipo ENUM('CL','EM') DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

--
-- Create index `FK_PERSONAS_USUARIOS_idx` on table `usuarios`
--
ALTER TABLE usuarios 
  ADD INDEX FK_PERSONAS_USUARIOS_idx(personas_id);

--
-- Create foreign key
--
ALTER TABLE usuarios 
  ADD CONSTRAINT FK_PERSONAS_USUARIOS FOREIGN KEY (personas_id)
    REFERENCES personas(id);

--
-- Create table `sesiones`
--
CREATE TABLE IF NOT EXISTS sesiones (
  id INT NOT NULL AUTO_INCREMENT,
  estado ENUM('CO','FA') DEFAULT NULL,
  fechahora DATETIME DEFAULT CURRENT_TIMESTAMP,
  usuarios_id INT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

--
-- Create index `FK_USUARIO_SESIONES_idx` on table `sesiones`
--
ALTER TABLE sesiones 
  ADD INDEX FK_USUARIO_SESIONES_idx(usuarios_id);

--
-- Create foreign key
--
ALTER TABLE sesiones 
  ADD CONSTRAINT FK_USUARIO_SESIONES FOREIGN KEY (usuarios_id)
    REFERENCES usuarios(id);

--
-- Create table `tipos`
--
CREATE TABLE IF NOT EXISTS tipos (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  activo TINYINT NOT NULL DEFAULT 1,
  imagen VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

--
-- Create table `productos`
--
CREATE TABLE IF NOT EXISTS productos (
  id INT NOT NULL AUTO_INCREMENT,
  codigobarras VARCHAR(45) DEFAULT NULL,
  codigocatalogo VARCHAR(45) DEFAULT NULL,
  nombre VARCHAR(45) NOT NULL,
  descripcion VARCHAR(250) DEFAULT NULL,
  impuesto DOUBLE DEFAULT NULL,
  precio DOUBLE DEFAULT NULL,
  activo TINYINT DEFAULT 1,
  idtipo INT DEFAULT NULL,
  imagen VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

--
-- Create index `FL_TIPO_PRODUCTOS_idx` on table `productos`
--
ALTER TABLE productos 
  ADD INDEX FL_TIPO_PRODUCTOS_idx(idtipo);

--
-- Create foreign key
--
ALTER TABLE productos 
  ADD CONSTRAINT FL_TIPO_PRODUCTOS FOREIGN KEY (idtipo)
    REFERENCES tipos(id);

-- 
-- Dumping data for table personas
--
INSERT INTO personas VALUES
(1, 'Luis', 'Flores', '96362917', 1, 'persona.png');

-- 
-- Dumping data for table usuarios
--
-- Table medi.usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table tipos
--
-- Table medi.tipos does not contain any data (it is empty)

-- 
-- Dumping data for table sesiones
--
-- Table medi.sesiones does not contain any data (it is empty)

-- 
-- Dumping data for table productos
--
-- Table medi.productos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;